### ISSUE TITLE
InteractiveChat - Unhandled exception occured in onPacketSending

### ISSUE THREAD

**Issue by TheCiROMG** [pl3xgaming/Purpur#194] opened 2021-03-10 13:57 UTC
![Captura de pantalla 2021-03-10 105608](https://user-images.githubusercontent.com/61605643/110640239-57e71300-818f-11eb-89dc-c76588ae4739.png)

**Comment by katekerllenevich** [comment] 2021-03-10 13:58
Thats an issue with paper/adventure.

**Comment by TheCiROMG** [comment] 2021-03-10 14:01
They already patched it next to tuinity... but purpur doesn't have that patch...

**Comment by BillyGalbreath** [comment] 2021-03-10 18:37
1) This is a bug caused by the Paper adventure update.
2) Tuinity never merged in the adventure updates, so never had the issues.
3) Purpur is up to date with Paper in regards of these adventure bugs.
4) The bug reported is _actually_ a bug in ProtocolLib and has already been fixed in that plugin <https://github.com/dmulloy2/ProtocolLib/pull/1103>
5) Making false claims like "Tuinity already fixed this" only slows down development as I have to chase around false leads looking for the solution to reported issues. Next time instead of spending so much time fabricating information you might want to redirect those efforts into proper research before making a report. Then maybe you would find the solution yourself without the embarrassment.

**Closed as completed by BillyGalbreath** 2021-03-10 18:37 UTC
