### ISSUE TITLE
Every time I turn on the server, it crashes

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [pl3xgaming/Purpur#1427] opened 2023-09-07 15:29 UTC
### Spark link

https://spark.lucko.me/O8UX4cIQ9c

### Stack trace

```
https://paste.gg/p/anonymous/0628884134384925a326b01d8e3bfc28
```

### Purpur version

[17:23:55 INFO]: CMI: 9.6.2.5 BungeeCord MySQL-> 9.6.2.6
[17:23:55 INFO]: CMILib: 1.4.1.1
[17:23:55 INFO]: Server: Purpur 1.20.1-R0.1-SNAPSHOT
[17:23:55 INFO]: CMI economy: POVOLENO Vault: 1.7.3-b131(CMIEInjector) CMI Chat: ZAKAZÁNO
[17:23:55 INFO]: Modules -> 44 enabled 15 disabled: spawnerProximity, mirror, tablist, armorEffects, moneyCheque, skin, noTarget, elytraBoost, paintingEditor, playerChatTag, flightCharge, disabledEnchants, chatBubble, spawnerCharge, namePlates

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Hello, I have been using Purpur for a very long time and I am very satisfied. However, I am experiencing one problem when turning on the server.

Every time I turn on the server, the server shuts itself down, it writes th
e message "DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH" etc.. see attached link.
However, as soon as it shuts down, it comes back up again and then everything is fine. It's always just the first power up. It's been doing this since 1.19.4, I've already updated probably every plugin and switched to 1.20, but I still have the same problem.
Thank you

[2023-09-06-5.log](https://github.com/PurpurMC/Purpur/files/12550888/2023-09-06-5.log)

**Comment by Huge-mistake** [comment] 2023-09-08 11:00
DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH
It could be a problem with your server plugin
Or have you tried testing with upstream paper/pufferfish?
See if you get the same result

**Comment by granny** [comment] 2023-09-11 01:11
> DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH
> It could be a problem with your server plugin
> Or have you tried testing with upstream paper/pufferfish?
> See if you get the same result


What the person who deleted their message said ^

**Comment by Sh3r1ffCZ** [comment] 2023-09-11 08:36
I tried the new version of Purpur#2054 and the latest Paper#174.
Unfortunately the crash still persists with Purpur and with Paper the server started immediately on the first boot

**Comment by granny** [comment] 2023-09-11 08:36
Could you also test it with the latest version of Pufferfish?

**Comment by Sh3r1ffCZ** [comment] 2023-09-12 06:36
I put the latest build of Pufferfish and so far no problem. Looks like the problem has been solved by this, thank you. I'll probably stick with this one

**Comment by granny** [comment] 2023-09-12 09:47
That was not my intention. I asked you to test on Paper and Pufferfish to verify that it is actually a Purpur issue.

Are you able to replicate this with a clean test Purpur server that has no plugins installed? It's difficult to find a way to replicate your issue since there's so many variables that could be at play here. I need steps on how to reproduce the problem as well.

**Comment by Sh3r1ffCZ** [comment] 2023-09-12 10:44
That is the problem, I tried a clean server where I put ALL the plugins I have on this server where I am solving the problem. Unfortunately, the error didn't occur there. That's why it's also hard to determine what's actually causing the problem. I don't know why that is, but I know pufferfish doesn't have a problem with it. The server has been running for over 3 years and I have had this problem since 1.19.4, I was just hoping that 1.20.1, would solve this problem.

**Comment by granny** [comment] 2023-09-13 07:27
That's very weird.

I'd like to note that the server doesn't necessarily crash;  It just takes forever trying to load the chunk where a villager's POI exists, so the watchdog gets triggered. We don't apply any changes in that area, so it's very unlikely that it's a Purpur issue. I couldn't tell you why it seems to subside when using Paper or Pufferfish, though.

Closing since I don't think there's anything I can do about this. If you'd like, you can try joining our discord to see if someone can help you figure out what's wrong with your server.

**Closed as not planned by granny** 2023-09-13 07:27 UTC
Labels: question
