### ISSUE TITLE
Infinity works-without-arrows bug

### ISSUE THREAD

**Issue by SkeletonAce** [pl3xgaming/Purpur#778] opened 2021-12-10 21:12 UTC
### Expected behavior

When shooting with a bow and having a shield in your off-hand
You should change the bow without blocking at the same time.

### Observed/Actual behavior

With the setting, infinity works without arrows.

You charge the bow while blocking with the shield and can shoot while blocking.

(The player blocks with the shield while charging the bow)

### Steps/models to reproduce

enable:
 infinity-bow:
        works-without-arrows: true
        
 Use an infinity bow without any arrows in your inventory and use a shield in your off-hand.

### Purpur version

purpur-1.17.1-1428

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by encode42** [comment] 2021-12-10 21:25
Duplicate of #492

**Closed as completed by encode42** 2021-12-10 21:25 UTC
