### ISSUE TITLE
Purpur breaks weatcher thunder

### ISSUE THREAD

**Issue by Tizooo** [pl3xgaming/Purpur#851] opened 2022-01-17 01:49 UTC
### Expected behavior

i expected to see thunders

### Observed/Actual behavior

i didnt see any thunders

### Steps/models to reproduce

use purpur and do /weather thunder and no thunder will appear

### Purpur version

[02:48:42 INFO]: This server is running Paper version git-Paper-155 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 99cf01f)
You are running the latest version
Previous version: git-Purpur-1508 (MC: 1.18.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

if i use paper thunder works fine

**Comment by katekerllenevich** [comment] 2022-01-17 01:51
Please send a timings report as requested by the issue template!

**Comment by Tizooo** [comment] 2022-01-17 02:06
https://timings.aikar.co/?id=bc41be61e44a4a6ea8f0864764c86e29

**Comment by BillyGalbreath** [comment] 2022-01-17 02:17
Confirmed no thunder. Same for Paper build 155. Closing due to being upstream issue.

**Closed as completed by BillyGalbreath** 2022-01-17 02:17 UTC
Labels: upstream

**Comment by BillyGalbreath** [comment] 2022-01-18 00:14
Turned out lightning was fine on Paper, I just couldn't see it because of my shader pack.

Dug a little deeper into this issue and found it to be Pufferfish's fault. More specifically, Pufferfish inherited the issue from Airplane breaking a patch when Paul updated to 1.17

I've fixed the issue in Purpur build 1511

https://github.com/PurpurMC/Purpur/commit/90f8beddd406ec545835dd822c174d93972e0a17

**Comment by kev626** [comment] 2022-01-18 00:18
Patched upstream in https://github.com/pufferfish-gg/Pufferfish/commit/99a590b1bcb0c5b51f06015b990fc42e7eff76b8
