### ISSUE TITLE
Chunks not loading properly

### ISSUE THREAD

**Issue by mrpunky** [pl3xgaming/Purpur#926] opened 2022-03-08 14:47 UTC
### Description of issue

https://www.youtube.com/watch?v=CimfTkVZyN0

Even though I don't have a problem with 20 30 players, after 50 60 players, the chunks don't really load as in the video.

### Purpur version

![image](https://user-images.githubusercontent.com/66686400/157258430-b65d7001-9ec0-44cf-87a6-6d9d68191f8a.png)

But even if I update, this problem will continue because my problem continues regardless of the version.

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

I don't have a problem when I use "paper-1.18.1-201.jar" version, I have chunk problem when I use any paper or purpur version other than this version

Spark: https://spark.lucko.me/VSkqr6wnGj

![image](https://user-images.githubusercontent.com/66686400/157258995-f434603c-06a9-41ce-b892-1da573ce3cdb.png)
my guess is something done in this update is breaking it

**Comment by granny** [comment] 2022-03-08 15:20
> I have chunk problem when I use any paper ... version other than this version

Sounds like this is an issue with paper, not purpur. Create a report on their issue tracker (if they don't have one open already) with all the steps you took to create this one, just make sure you omit anything that remotely mentions pufferfish or purpur (they will close the issue without looking at it otherwise). In this case, reproduce on the latest version of paper, and attempt to reproduce on the build before the supposed change that brought about this bug.

> * You are 1 version(s) behind

> - [x] I am running the latest version of Purpur available from https://purpurmc.org/downloads.

This would usually be enough to close this issue (this time the reason being that the issue is upstream). Keep in mind that even if you know that being on the latest version doesn't change anything, if we don't see that reproduced on the **latest** version then there's no real guarantee that it's an issue we have to look into (since there's still a chance that it's been fixed in the latest build).

**Closed as completed by granny** 2022-03-08 15:20 UTC

**Comment by mrpunky** [comment] 2022-03-08 16:14
I set the value of "max-concurrent-sends: 2" to 10 and my problem is solved, I hope someone who gets this error will see it and the error will be resolved, thanks again.
