### ISSUE TITLE
Failed to save chunk because of NoSuchFileException

### ISSUE THREAD

**Issue by jungwuk-ryu** [pl3xgaming/Purpur#894] opened 2022-02-07 08:57 UTC
### Timings link

https://timings.aikar.co/?id=f6d45ecd60d94e529e8fae11155af432

### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://paste.gg/p/anonymous/b9e470c69aa64574a1efb42a45303b78  
Crash dump of Purpur 1537. **But 1547 has this problem too.**

### Purpur version

> version
[17:46:21 INFO]: Current: git-Purpur-1547 (MC: 1.18.1)*
[17:46:21 INFO]: Previous: git-Purpur-1537 (MC: 1.18.1)
[17:46:21 INFO]: * You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

It causes memory leak (or OOM)
We can fix this problem by deleting a region file. (Size of the file is 0KB) But it will happen again on other region.

Console log: https://paste.gg/p/anonymous/d8661a5edd314956a85a411a9bd32859
**그런 파일이나 디렉터리가 없습니다** means **No such file or directory** (but the region file exists)

**Comment by BillyGalbreath** [comment] 2022-02-08 18:48
This one looks like it's caused by a cheating player. They are logging out while teleporting through a nether portal.

This is caused by the disconnect method doing one last tick on the Player before disconnecting them. I am not sure why, but it looks to be added by Spigot to fix a bug. Unfortunately, that bug is private so I don't know why it's there or if its safe for me to fix this by removing that call when a player is standing in a portal. (https://hub.spigotmc.org/jira/browse/SPIGOT-924)

I'm trying to find out what SPIGOT-924 fixes, but I may never find out since it's private. You're best bet is to reproduce this as far upstream as possible to get people with access to see that ticket to make a decision on how to fix.

**Comment by BillyGalbreath** [comment] 2022-02-18 09:25
Unfortunately, I was unable to learn the secrets of SPIGOT-924 so I am forced to close this without applying any fixes. I could easily reintroduce a severe bug by fixing this one for all I know (most likely a dupe, since its so secret). The only advice I can give is to recreate this further upstream where they may have more insight than I am privy to.

**Closed as completed by BillyGalbreath** 2022-02-18 09:25 UTC
