### ISSUE TITLE
PlayerPortalEvent returns wrong Y location for event.getTo

### ISSUE THREAD

**Issue by xGinko** [pl3xgaming/Purpur#1191] opened 2022-11-14 13:53 UTC
### Spark link

https://spark.lucko.me/SUlAroLJGy

### Expected behavior

When listening to PlayerPortalEvent, the method .getTo() returning the correct Y location of the destination location.

### Observed/Actual behavior

the Y location from event.getFrom() is returned instead, everything else returns just fine:
```
Event from = Location{world=CraftWorld{name=world_nether},x=-39.65024695332261,y=129.0,z=-2.1308751958137777,pitch=7.952062,yaw=-89.24747}
Event to = Location{world=CraftWorld{name=world},x=-318.0,y=129.0,z=-18.0,pitch=7.952062,yaw=-89.24747}
```
**the correct to Y-Location here shouldve been -54**

### Steps/models to reproduce

Listen to PlayerPortalEvent using:
```
Bukkit.getLogger().info("Event from = "+event.getFrom());
Bukkit.getLogger().info("Event to = "+event.getTo());
```

### Purpur version

[14:47:54 INFO]: Current: git-Purpur-1842 (MC: 1.19.2)*
Previous: git-Purpur-1838 (MC: 1.19.2)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by xGinko** [comment] 2022-11-14 14:07
This also happens when listening to EntityPortalEvent.

**Comment by BillyGalbreath** [comment] 2022-12-13 07:38
Are you able to recreate this upstream?

**Comment by BillyGalbreath** [comment] 2022-12-15 16:40
I can confirm this issue is present upstream on the latest Paper build.

```
[10:39:05 INFO]: BillyGalbreath joined the game
[10:39:05 INFO]: BillyGalbreath[/127.0.0.1:43698] logged in with entity id 158 at ([world_nether]5.757473117615233, 83.0, 29.674693567766205)
[10:39:17 INFO]: [Test] [STDOUT] BillyGalbreath has used a portal!
[10:39:17 WARN]: Nag author(s): '[]' of 'Test' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[10:39:17 INFO]: [Test] [STDOUT]   From: Location{world=CraftWorld{name=world_nether},x=4.434401475671042,y=83.0,z=24.03791094611653,pitch=11.699776,yaw=168.9007}
[10:39:17 INFO]: [Test] [STDOUT]   To: Location{world=CraftWorld{name=world},x=35.0,y=83.0,z=192.0,pitch=11.699776,yaw=168.9007}
[10:39:22 INFO]: [Test] [STDOUT] BillyGalbreath has used a portal!
[10:39:22 INFO]: [Test] [STDOUT]   From: Location{world=CraftWorld{name=world},x=36.0527334185952,y=64.0,z=186.07228920472699,pitch=17.399761,yaw=0.29916382}
[10:39:22 INFO]: [Test] [STDOUT]   To: Location{world=CraftWorld{name=world_nether},x=4.0,y=64.0,z=23.0,pitch=17.399761,yaw=0.29916382}
[10:39:23 INFO]: [Test] [STDOUT] BillyGalbreath has used a portal!
[10:39:23 INFO]: [Test] [STDOUT]   From: Location{world=CraftWorld{name=world_nether},x=3.656401916059541,y=83.0,z=24.06722615274769,pitch=12.599773,yaw=-179.40062}
[10:39:23 INFO]: [Test] [STDOUT]   To: Location{world=CraftWorld{name=world},x=29.0,y=83.0,z=192.0,pitch=12.599773,yaw=-179.40062}
> version
[10:39:34 INFO]: Checking version, please wait...
[10:39:35 INFO]: This server is running Paper version git-Paper-334 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 20503be)
You are running the latest version
Previous version: git-Purpur-"082734f" (MC: 1.19.3)
```

Closing as upstream issue.

**Closed as completed by BillyGalbreath** 2022-12-15 16:40 UTC
Labels: upstream

**Comment by Machine-Maker** [comment] 2022-12-15 18:06
This is actually correct as far as I can tell. That is the location it starts the portal search. This event is called before the portal is searched for or created (hence the options for search radius and a "create" bool). The "to" position is literally only the "from" position with the X and Z coords scaled for the dimension scaling.

For end portals, it is the exact destination, since that doesn't require any "searching".

**Comment by BillyGalbreath** [comment] 2022-12-15 18:07
Interesting. Should probably update the JavaDoc to document that behavior if it is indeed intended. Kinda makes this event useless, though.

**Comment by Machine-Maker** [comment] 2022-12-15 18:15
> Should probably update the JavaDoc to document that behavior if it is indeed intended.

yes absolutely

> Kinda makes this event useless, though.

nah, don't think so. You can use the teleport event with that specific cause which is fired after to change exactly where they go. This event's main purpose is to control nether portal searches.
