### ISSUE TITLE
 Encountered an unexpected exception net.minecraft.ReportedException: Exception ticking world

### ISSUE THREAD

**Issue by taka1945** [pl3xgaming/Purpur#467] opened 2021-07-04 06:11 UTC
### Expected behavior

after upgarde to puper 1.17-1247 ... 
now i just switch back to 1.17 #1235 it run normal.

### Observed/Actual behavior

[13:12:52] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1647) ~[patched_1.17.jar:git-Purpur-1247]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.jar:git-Purpur-1247]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1478) ~[patched_1.17.jar:git-Purpur-1247]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1262) ~[patched_1.17.jar:git-Purpur-1247]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[patched_1.17.jar:git-Purpur-1247]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.h(net.minecraft.world.entity.Entity)" because "entity" is null
	at com.tuinity.tuinity.util.CollisionUtil.getEntityHardCollisions(CollisionUtil.java:568) ~[patched_1.17.jar:git-Purpur-1247]
	at net.minecraft.world.level.CollisionGetter.noCollision(CollisionGetter.java:49) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.isValidSpawnPostitionForType(NaturalSpawner.java:367) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:283) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:216) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:196) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1034) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:932) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:794) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1627) ~[patched_1.17.jar:git-Purpur-1247]

### Steps/models to reproduce

Chances occur after the player gives a command, such as teleporting home ,
server just crash down.

### Purpur version

puper 1.17-1247

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by jpenilla** [comment] 2021-07-04 06:13
Duplicate of https://github.com/Tuinity/Tuinity/issues/331

**Closed as completed by jpenilla** 2021-07-04 06:13 UTC
