### ISSUE TITLE
Minecarts are not controllable

### ISSUE THREAD

**Issue by Kaiiak04** [pl3xgaming/Purpur#1628] opened 2024-12-30 02:40 UTC
### Spark link

https://spark.lucko.me/zpPqDkStXL

### Expected behavior

Minecarts should be controllable using the WASD keys.

### Observed/Actual behavior

Minecarts are able to be placed and entered, and are able to turn with the player, but cannot move using the WASD keys.

### Steps/models to reproduce

1. Create a Purpur server with the latest version of 1.21.3 Purpur (1.21.3-2358-16ce24a), and enable place-anywhere and controllable settings in the purpur.yml file.
2. Place a minecart and ride it. You will see that you can turn around, but you can't move

### Purpur version

Current Purpur Version: 1.21.3-2358-16ce24a (MC: 1.21.3)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment] 2024-12-30 02:51
duplicate of https://github.com/PurpurMC/Purpur/issues/1624

fixes will not be backported

**Closed as not planned by granny** 2024-12-30 02:51 UTC
