### ISSUE TITLE
silk-spawners setting in config turns spawners into pig spawners.

### ISSUE THREAD

**Issue by dev-stan** [pl3xgaming/Purpur#142] opened 2021-01-12 19:42 UTC
After enabling the `silk-touch` setting in `purpur.yml`, broken spawners are renamed as they should, though after placing those broken spawners they turn into pig spawners.

To reproduce; assign a group the `purpur.place.spawners` and `purpur.drop.spawners` permission nodes.

**Comment by JanTuck** [comment] 2021-01-12 19:43
Was this reproduced without any plugins?

**Comment by granny** [comment] 2021-01-12 19:55
duplicate of #48

**Closed as completed by granny** 2021-01-12 19:55 UTC
Labels: duplicate
