### ISSUE TITLE
Structure-seeds are broken

### ISSUE THREAD

**Issue by IceWaffles** [pl3xgaming/Purpur#789] opened 2021-12-15 11:59 UTC
### Timings link

https://timings.aikar.co/?id=efaee583ca404dbea5700991f3ae42e9#config

### Expected behavior

Strongholds & mineshafts have some change in generation after modified the seeds under structure-seeds in `purpur.yml`.

### Observed/Actual behavior

They end up looking like the exact same. ie if you went and changed the seeds in `purpur.yml` and generated a normal, vanilla world. If you go to both the exact same coordinates, you will not only find the same [structure, eg stronghold] there, but actually them being of no difference at all in generation.

*Have not tested at all for buried-treasures.

### Steps/models to reproduce

Simply create a world with Purpur having modified structure seeds (in this case, strongholds or mineshafts) and compare it with an unmodified vanilla world (eg on singleplayer) with the same seed.

### Purpur version

[11:46:16 INFO]: Checking version, please wait...
[11:46:17 INFO]: This server is running Purpur version git-Purpur-1438 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: aa425ec on HEAD)
[11:46:17 INFO]: You are running the latest version
[11:46:17 INFO]: Previous version: git-Paper-75 (MC: 1.18.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Attached two screenshots below-both are of stronghold on the same seed, except one world had Purpur.yml modifying it [stronghold] to a different seed.

<img width="1440" alt="Screenshot 2021-12-15 at 11 44 33 AM" src="https://user-images.githubusercontent.com/86599175/146181610-d187ae84-b44f-4384-89fd-81f5dd0352c7.png">
<img width="1440" alt="Screenshot 2021-12-15 at 11 43 45 AM" src="https://user-images.githubusercontent.com/86599175/146181614-74ffa344-7c03-4658-8d9c-5bb1587736c1.png">

**Comment by katekerllenevich** [comment] 2021-12-15 12:17
Duplicate of #691

**Closed as completed by katekerllenevich** 2021-12-15 12:17 UTC
