### ISSUE TITLE
Silk-Spawners always turn to Pig Spawners

### ISSUE THREAD

**Issue by kohy-creates** [pl3xgaming/Purpur#238] opened 2021-03-25 09:52 UTC
**Describe the bug**
All placed spawners turn to Pig Spawners (spawners mined with Silk Touch when Purpu's Silk-Spawners are ON)

**To Reproduce**
Mine e.g. Creeper spawner and place it

**Plugins**
Plugins (28): ChestShop, Chunky, Citizens, eco, EcoEnchants, GriefPrevention, HeadDatabase, HolographicDisplays, LibsDisguises, LuckPerms, Multiverse-Core, OpenAudioMc, ProtocolLib, SkBee, skDragon, SkQuery, Skript, skript-reflect, Tablisknu, ThatPacketAddon*, TheNewEconomy, TuSKe*, Vault, Vixio*, Votifier, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

**Version**
This server is running Purpur version git-Purpur-1038 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 4 version(s) behind
Previous version: git-Purpur-1025 (MC: 1.16.5)

**Comment by granny** [comment] 2021-03-25 10:48
duplicate of #48.

Make sure to read https://github.com/pl3xgaming/Purpur/issues/48#issuecomment-686179684

**Closed as completed by granny** 2021-03-25 10:48 UTC
Labels: duplicate
