### ISSUE TITLE
silk-touch spawner setting turning into pig spawners.

### ISSUE THREAD

**Issue by dev-stan** [pl3xgaming/Purpur#143] opened 2021-01-12 19:43 UTC
After enabling the `silk-touch` setting in `purpur.yml`, broken spawners are renamed as they should, though after placing those broken spawners they turn into pig spawners.

To reproduce; assign a group the `purpur.place.spawners` and `purpur.drop.spawners` permission nodes.

**Comment by JanTuck** [comment] 2021-01-12 19:45
Duplicate of https://github.com/pl3xgaming/Purpur/issues/142

**Closed as completed** 2021-01-12 19:46 UTC
