### ISSUE TITLE
Purpur Profile Lookup Executor?

### ISSUE THREAD

**Issue by Skizzles** [pl3xgaming/Purpur#947] opened 2022-03-28 19:59 UTC
### Timings link

N/A

### Expected behavior

Not quite sure to be honest.

### Observed/Actual behavior

This error seems to be given on login.

### Steps/models to reproduce

I believe this may be related to having Geyser and Bedrock users join with "-" prefix.

### Purpur version

purpur-1.18.2-1598.jar

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

[12:41:25 FATAL]: Uncaught exception in thread Profile Lookup Executor #1
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.2.38.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200) ~[authlib-3.2.38.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[purpur-1.18.1.jar:git-Purpur-1566]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187) ~[authlib-3.2.38.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[purpur-1.18.1.jar:git-Purpur-1566]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$3(SkullBlockEntity.java:155) ~[?:?]
        at net.minecraft.Util.ifElse(Util.java:440) ~[?:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$6(SkullBlockEntity.java:152) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by BillyGalbreath** [comment] 2022-03-28 20:03
Duplicate of #889

**Closed as completed by BillyGalbreath** 2022-03-28 20:03 UTC
