### ISSUE TITLE
custom player head lose textures

### ISSUE THREAD

**Issue by JellyRoad** [pl3xgaming/Purpur#1413] opened 2023-08-15 20:14 UTC
### Spark link

https://spark.lucko.me/72G1TAmXCO

### Expected behavior

https://github.com/PurpurMC/Purpur/assets/73968499/f8319b3d-9464-4ddf-bcaf-8a80d703aca0

### Observed/Actual behavior

https://github.com/PurpurMC/Purpur/assets/73968499/d2e9c875-c820-436f-ac2d-040317cb0f2a

### Steps/models to reproduce

start paper server 
stop the server
go to server files
open world folder
open datapacks folder
put Decapitation.zip into datapacks folder  
[Decapitation.zip](https://github.com/PurpurMC/Purpur/files/12352687/Decapitation.zip)
start srver
summon warden and kill him
pick up head that he drop
try to open inventory/place head

### Purpur version

Current: git-Purpur-2035 (MC: 1.20.1)*\nPrevious: git-Paper-127 (MC: 1.20.1)\n* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

Data for heads
in first slot normal head (how it shuld look like)
in second slot broken head

/setblock -1 76 24 minecraft:chest[facing=south,type=single,waterlogged=false]{Items:[{Count:1b,Slot:0b,id:"minecraft:player_head",tag:{SkullOwner:{Id:[I;1553579158,176833303,-1716217748,-1737146209],Name:"Warden",Properties:{textures:[{Signature:'{"italic":false,"color":"yellow","text":"Warden Head"}',Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzk1OWFlMDJlMzVjYmM0NzQzZTZlNzAyZmRhNjk4MGJhZDJlOTgwNDk0MDNjMTY5OTYyODZlYjQxMmY5NDY4OSJ9fX0="},{Signature:"tdp.511:sounds/warden",Value:"TDP511_V1"},{Signature:'{"text":"Player Kill","color":"#11BB11","italic":false}',Value:'{"text":"Obtained from:","color":"#888888","italic":false}'},{Signature:"tdp.511:sounds/warden",Value:"TDP511_V1"}]}},display:{Lore:['{"text":"Obtained from:","color":"#888888","italic":false}','{"text":"Player Kill","color":"#11BB11","italic":false}'],Name:'{"italic":false,"color":"yellow","text":"Warden Head"}'}}},{Count:1b,Slot:1b,id:"minecraft:player_head",tag:{SkullOwner:{Id:[I;1553579158,176833303,-1716217748,-1737146209],Name:"Warden",Properties:{textures:[{Signature:"tdp.511:sounds/warden",Value:"TDP511_V1"}]}},display:{Lore:['{"text":"Obtained from:","color":"#888888","italic":false}','{"text":"Player Kill","color":"#11BB11","italic":false}'],Name:'{"italic":false,"color":"yellow","text":"Warden Head"}'}}}]}

**Comment by TheDiamondPlayables** [comment] 2023-08-16 01:24
A related thread is also posted on Paper's bug reports, and it's been confirmed there:
https://github.com/PaperMC/Paper/issues/9612
Here's where the issue came from for Paper: https://github.com/PaperMC/Paper/blob/master/patches/server/0427-Clean-up-duplicated-GameProfile-Properties.patch
Since Purpur is a Paper fork, I'd assume this isn't changed yet since the same issue exists on both JARs. 
But it would be pretty helpful if you guys could do something about it. Thanks!

**Comment by JamieIsGeek** [comment] 2023-08-17 19:48
Just made a PR for this on Papers end - will fix when upstream is next updated

**Comment by JamieIsGeek** [comment] 2023-08-17 21:00
Merged into Paper, will fix on upstream update

**Closed as not planned** 2023-08-17 23:15 UTC
Labels: upstream
