### ISSUE TITLE
The server stopped on its own for the first time in 2 years...

### ISSUE THREAD

**Issue by foxya27** [pl3xgaming/Purpur#1572] opened 2024-08-01 13:38 UTC
### Spark link

Nothing

### Stack trace

```
https://paste.gg/p/anonymous/2681aac952684e60aaebb1b0ac85be37
```

### Actions to reproduce (if known)

I don’t know, the server just stopped, without crashing, like with the stop command

### Purpur version

1.21-2278-b3623fa (MC: 1.21)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

[16:06:42] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1849) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read field "table" because "newChain" is null
	at ca.spottedleaf.concurrentutil.map.ConcurrentLong2ReferenceChainedHashTable$NodeIterator.pullResizeChain(ConcurrentLong2ReferenceChainedHashTable.java:1470) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at ca.spottedleaf.concurrentutil.map.ConcurrentLong2ReferenceChainedHashTable$NodeIterator.findNext(ConcurrentLong2ReferenceChainedHashTable.java:1548) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at ca.spottedleaf.concurrentutil.map.ConcurrentLong2ReferenceChainedHashTable$BaseIteratorImpl.hasNext(ConcurrentLong2ReferenceChainedHashTable.java:1404) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:728) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:90) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:400) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:710) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1843) ~[purpur-1.21.jar:1.21-2278-b3623fa]
	... 5 more
[16:06:42] [Server thread/ERROR]: This crash report has been saved to: /home/dfuser/DreamFox/crash-reports/crash-2024-08-01_16.06.42-server.txt
[16:06:42] [Server thread/INFO]: Stopping server

**Comment by Krakenied** [comment] 2024-08-01 13:44
`without crashing` but you literally pasted a crash report

**Comment by foxya27** [comment] 2024-08-01 13:46
> `without crashing` but you literally pasted a crash report

I understand, sorry for my English, but it was a crash

**Comment by Onako2** [comment] 2024-08-01 13:46
You don't have to post it twice, could we continue on Discord?

**Comment by foxya27** [comment] 2024-08-01 13:46
It’s just that earlier, in my understanding, a crash was when the server simply turned off without saving chunks and other things.

**Comment by Krakenied** [comment] 2024-08-01 13:47
The issue seems to be caused by the new Paper chunk system - you are running latest Purpur so I would try searching for a similar issue on Paper issues

**Comment by foxya27** [comment] 2024-08-01 13:47
> You don't have to post it twice, could we continue on Discord?

yep

**Comment by foxya27** [comment] 2024-08-01 13:48
> The issue seems to be caused by the new Paper chunk system - you are running latest Purpur so I would try searching for a similar issue on Paper issues

This was the first thing I did, either I didn’t see it or she’s not there

**Comment by Krakenied** [comment] 2024-08-01 13:49
Are you able to reproduce it?

**Comment by foxya27** [comment] 2024-08-01 13:53
> Are you able to reproduce it?

I think no

**Comment by foxya27** [comment] 2024-08-01 14:06
In general, I'll wait for an answer....

**Comment by Krakenied** [comment] 2024-08-02 14:56
Fixed in latest build (https://github.com/PurpurMC/Purpur/commit/930003b1d1826c083f3cee4db79621e6a7d726f1, https://github.com/PaperMC/Paper/commit/df3b654)

**Closed as completed** 2024-08-02 19:04 UTC
