### ISSUE TITLE
Enderchest 6 rows bug

### ISSUE THREAD

**Issue by sebberj** [pl3xgaming/Purpur#1367] opened 2023-06-27 15:20 UTC
### Spark link

https://spark.lucko.me/mop0IDREM1

### Expected behavior

I expected it to work ?? - I expected to get an enderchest with six rows, but when i click on the enderchest it won't open and i get a huge error in console.

### Observed/Actual behavior

I have luckperms installed on my server.

My group: Nybegynder has this permission; purpur.enderchest.rows.three
This works fine, i now have a enderchest with three rows.

Now i give my self this permission; purpur.enderchest.rows.six 
Now when i try to open my enderchest it gives this error:

`[17:08:23 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInUseItem@46318041, suppressing error
java.lang.IllegalArgumentException: Container size 27 is smaller than expected 54
        at net.minecraft.world.inventory.AbstractContainerMenu.checkContainerSize(AbstractContainerMenu.java:137) ~[?:?]
        at net.minecraft.world.inventory.ChestMenu.<init>(ChestMenu.java:100) ~[?:?]
        at net.minecraft.world.inventory.ChestMenu.sixRows(ChestMenu.java:95) ~[?:?]
        at net.minecraft.world.level.block.EnderChestBlock.lambda$use$1(EnderChestBlock.java:93) ~[?:?]
        at net.minecraft.world.SimpleMenuProvider.createMenu(SimpleMenuProvider.java:25) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1601) ~[?:?]
        at net.minecraft.world.level.block.EnderChestBlock.use(EnderChestBlock.java:87) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1177) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:583) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2043) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`
        
       

### Steps/models to reproduce

I have luckperms installed on my server.

My group: Nybegynder has this permission; purpur.enderchest.rows.three
This works fine, i now have a enderchest with three rows.

Now i give my self this permission; purpur.enderchest.rows.six 
Now when i try to open my enderchest it gives this error:

### Purpur version

> version
[17:14:49 INFO]: Checking version, please wait...
[17:14:49 INFO]: Current: git-Purpur-2004 (MC: 1.20.1)*
Previous: git-Purpur-2001 (MC: 1.20.1)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by RhythmicSys** [comment] 2023-06-29 03:39
For clarification, did this continue after a server restart, or did the error only occur initially enabling the option and reloading the config?

**Comment by sebberj** [comment] 2023-06-29 14:55
> For clarification, did this continue after a server restart, or did the error only occur initially enabling the option and reloading the config?

No the error does not occur when restarting the server. When restarting the server you have the 6 rows in the enderchest and no error in the console

**Comment by granny** [comment] 2023-07-03 04:20
I can't seem to reproduce your issue. To repeat Rhythmic's question, did you update the config by running `/purpur reload` or did you restart the server?

**Comment by sebberj** [comment] 2023-07-03 17:15
> I can't seem to reproduce your issue. To repeat Rhythmic's question, did you update the config by running `/purpur reload` or did you restart the server?

I restarted the server. 

Just to clarify

First i have the permission: purpur.enderchest.rows.three - then i give myself this permission: purpur.enderchest.rows.six
And now i can't open my enderchest and i gives me an error in console.

**Comment by Krakenied** [comment] 2023-07-05 23:11
It happens because row number is assigned to player on join
https://github.com/PurpurMC/Purpur/blob/ab2f1c06cef7ae6ff5f6754c87951eb406d60dbf/patches/server/0010-Barrels-and-enderchests-6-rows.patch#L16-L35
but permissions are always refreshed and
```
    // Purpur start
    @Override
    public int getContainerSize() {
        return owner.sixRowEnderchestSlotCount < 0 ? super.getContainerSize() : owner.sixRowEnderchestSlotCount;
    }
    // Purpur end
```
^ that method returns the value cached on join in code below
```
    public static ChestMenu fiveRows(int syncId, Inventory playerInventory, Container inventory) {
        return new ChestMenu(MenuType.GENERIC_9x5, syncId, playerInventory, inventory, 5);
```
```
    public ChestMenu(MenuType<?> type, int syncId, Inventory playerInventory, Container inventory, int rows) {
        super(type, syncId);
        checkContainerSize(inventory, rows * 9);
```
```
    protected static void checkContainerSize(Container inventory, int expectedSize) {
        int j = inventory.getContainerSize();

        if (j < expectedSize) {
            throw new IllegalArgumentException("Container size " + j + " is smaller than expected " + expectedSize);
```
```
[01:05:25 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInUseItem@7ff061b1, suppressing error
java.lang.IllegalArgumentException: Container size 27 is smaller than expected 54
        at net.minecraft.world.inventory.AbstractContainerMenu.checkContainerSize(AbstractContainerMenu.java:137) ~[?:?]
        at net.minecraft.world.inventory.ChestMenu.<init>(ChestMenu.java:100) ~[?:?]
        at net.minecraft.world.inventory.ChestMenu.sixRows(ChestMenu.java:95) ~[?:?]
        at net.minecraft.world.level.block.EnderChestBlock.lambda$use$1(EnderChestBlock.java:106) ~[?:?]
```

**Comment by granny** [comment] 2023-07-06 00:44
still unable to reproduce

**Comment by Krakenied** [comment] 2023-07-06 06:59
> still unable to reproduce
1. /lp user nick permission set purpur.enderchest.rows.four
2. Join the server, open enderchest and close it
3. /lp user nick permission unset purpur.enderchest.rows.four
4. /lp user nick permission set purpur.enderchest.rows.five
5. Open enderchest again
6. You can't do it, there is IllegalArgumentException in console

**Closed as completed** 2023-07-09 08:36 UTC
Labels: bug
