### ISSUE TITLE
Crash when destroying chests in The End

### ISSUE THREAD

**Issue by FastJoe0** [pl3xgaming/Purpur#700] opened 2021-10-07 05:24 UTC
### Timings link

none

### Stack trace

```
https://paste.gg/p/Marco/afa46f639e1d42c8b7b2731a0dab575d
```

### Actions to reproduce (if known)

The player destroys the chests (propably in world_the_end) and is then kicked with a "Packet processing" error. Finally, the server crashed.

I also see a few errors in the console after destroying the chest:
com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.world.level.block.entity.TileEntityChest@7c933c32) at -5659,151,9697 (Block{minecraft:air}) where there was no entity tile!

### Purpur version

This server is running Purpur version git-Purpur-1402 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b1810bb on ver/1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by Euphillya** [comment] 2021-10-07 05:32
Hello can you reproduce without a plugin?

**Comment by FastJoe0** [comment] 2021-10-07 05:48
Unfortunately, the reproduction is only my guess while reading the logs (I tried to destroy chests in The End but unfortunately it did not give the expected result). 

I teleported to the place of the player who caused the crash, but only the following appeared in the logs: https://paste.gg/p/Marco/481b0332256e4cd1a6a20b695683224c

I do not have a plugin that is responsible for special blocks/items and here it is about a corrupted tile entity

**Comment by Oharass** [comment] 2021-10-07 12:53
I find the reproduce and this does not happen on airplane or paper. Only purpur. Mountain of explosives is required.

**Comment by GunacP40** [comment] 2021-10-07 18:43
Having this exact same issue and it also happens with chests from other structures such as buried trasures.

**Comment by encode42** [comment] 2021-10-11 19:10
I believe this has been fixed in one of the recent upstream updates, as I cannot reproduce on the latest build (1406). Closing unless the issue persists.

**Closed as completed by encode42** 2021-10-11 19:10 UTC
