### ISSUE TITLE
Player head with wrong pitch and yaw

### ISSUE THREAD

**Issue by Maxlego08** [pl3xgaming/Purpur#1393] opened 2023-07-20 15:47 UTC
### Spark link

https://spark.lucko.me/dcmmjc7iPC

### Expected behavior

The heads must be correctly synchronized between the players and the server. Currently, this is not the case.

### Observed/Actual behavior

When connecting to a server, the head of all player entities will have their head with a pitch and a yaw of 0 . 0
Even if the player looks in another direction.

### Steps/models to reproduce

Video:
https://youtu.be/HSJpyEkurFU
Screen:
![image](https://github.com/PurpurMC/Purpur/assets/32517160/e512eb26-390c-408d-b076-9b5ec42c087f)

### Purpur version

![image](https://github.com/PurpurMC/Purpur/assets/32517160/22ef0b54-daa3-4ad3-9e0d-3c17339547c3)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment] 2023-07-20 16:28
Duplicate of #1382

**Closed as not planned** 2023-07-23 06:28 UTC
Labels: duplicate, invalid
